apiVersion: v1
kind: Service
metadata:
  name: nutrient-signing-service
  namespace: nutrient-services
  labels:
    app.kubernetes.io/name: nutrient-signing-service
    app.kubernetes.io/instance: nutrient-signing-service
spec:
  type: ClusterIP
  ports:
    - port: 6000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nutrient-signing-service
    app.kubernetes.io/instance: nutrient-signing-service
